#!/usr/bin/env bash

# install miniconda
cd ${HOME}
mkdir -p miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3/miniconda.sh
bash miniconda3/miniconda.sh -b -u -p miniconda3
rm -rf ${HOME}/miniconda3/miniconda.sh

# setup conda
export PATH="${HOME}/miniconda3/bin:${HOME}/miniconda3/condabin:$PATH"
source activate ${HOME}/miniconda3

# install mamba
conda install -y -c conda-forge mamba

# create the snakemake master env
mamba create -n "snakemake" -c conda-forge -c bioconda -c defaults python=3.8 snakemake pandas mamba -y
